site_name: Cloudgene 2.0.0 RC1
theme:
  name: material
  feature:
    tabs: true
extra_css:
  - extra.css
repo_url: https://github.com/genepi/cloudgene/
google_analytics: ['UA-873221-12', 'docs.cloudgene.io']
pages:

- Cloudgene:
    - Installation: index.md
    - Getting Started: daemon/getting-started.md
    - Configuration:
        - Settings File: daemon/configuration.md
        - Enable Hadoop Support: daemon/hadoop.md
        - Customization: daemon/customization.md
    - Install Applications: daemon/install-apps.md
    - Manage Permissions: daemon/permissions.md
    - Manage Jobs: daemon/jobs.md
    - Administration: daemon/administration.md

- Cloudgene CLI:
    - Introduction: cli/introduction.md
    - cloudgene install: cli/cloudgene-install.md
    - cloudgene github-install: cli/cloudgene-github-install.md
    - cloudgene clone: cli/cloudgene-clone.md
    - cloudgene remove: cli/cloudgene-remove.md
    - cloudgene ls: cli/cloudgene-ls.md
    - cloudgene validate: cli/cloudgene-validate.md
    - cloudgene verify-cluster: cli/cloudgene-verify-cluster.md
    - cloudgene run: cli/cloudgene-run.md
    - cloudgene server: cli/cloudgene-server.md
    - cloudgene version: cli/cloudgene-version.md

- Development:
    - Introduction: developers/introduction.md
    - Steps:
        - BashCommand: developers/steps/BashCommand.md
        - JavaJar: developers/steps/JavaJar.md
        - HadoopMapReduce: developers/steps/HadoopMapReduce.md
        - HadoopPig: developers/steps/HadoopPig.md
        - RMarkdown: developers/steps/RMarkdown.md
        - RMarkdown (Docker): developers/steps/RMarkdownDocker.md
        - HTML-Widget: developers/steps/HtmlWidget.md
        - Docker: developers/steps/Docker.md
        - JavaInterface: developers/steps/JavaInterface.md
        - Groovy: developers/steps/Groovy.md
    - Inputs:
      - Introduction: developers/inputs.md
      - Files and Folders: developers/inputs/files-folders.md
      - Text: developers/inputs/text.md
      - Number: developers/inputs/number.md
      - List: developers/inputs/list.md
      - Radio: developers/inputs/radio.md
      - Checkbox: developers/inputs/checkbox.md
      - App List: developers/inputs/app-list.md
      - Terms Checkbox: developers/inputs/terms_checkbox.md
      - Layout: developers/inputs/layout.md
    - Outputs: developers/outputs.md
    - Environment Variables: developers/environment_variables.md
    - Control patterns: developers/control-patterns.md

- Tutorials:
    - Using AppLinks to link to other applications: tutorials/application-links.md
    - Using InstallActions to import HDFS files: tutorials/installation-actions.md

- API Reference:
    - Introduction: api/introduction.md
    - Authentication: api/authentication.md
    - Submit Job: api/job-submission.md
    - Job Status: api/job-status.md
    - List Jobs: api/list-jobs.md
    - Job Details: api/job-details.md


extra:
  feature:
    tabs: true


markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true
  - footnotes
