micronaut:
  application:
    name: cloudgene
  server:
    port: 8080
    netty:
      default:
        allocator:
          max-order: 3
      access-logger:
        enabled: true
        logger-name: my-access-logger
        log-format: common    
  security:
      authentication: bearer
      intercept-url-map:
        - pattern : /api/**
          access:
            - isAuthenticated()
        - pattern : /static/**
          access:
            - isAnonymous()
        - pattern : /**
          access:
            - isAnonymous()
      token:
        bearer:
          header-name: "X-Auth-Token"
          prefix: ""
        jwt:
          generator:
            access-token:
              expiration: 86400
          signatures:
            secret:
              generator:
                secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
      redirect:
        enabled: false

      endpoints:
        login:
           enabled: false
        logout:
           get-allowed: true

  router:
    static-resources:
      webapp:
        mapping: "${micronaut.server.context-path:}/**"
        paths:
          - file:webapp
        enabled: true
      pages:
        enabled: true
        mapping: "${micronaut.server.context-path:}/static/**"
        paths:
          - file:pages
          - file:sample/pages
  views:
    folder: webapp
  serde:
    serialization:
      inclusion: ALWAYS
